[package]
name = "bender-worker"
version = "0.1.0"
authors = ["David Huss <dh@widerstandzwecklos.at>"]

[dependencies]
app_dirs = "1.2"
uuid = { version = "0.7", features = ["serde", "v4"] }
fs2 = "0.4"
itertools = "0.7"
dialoguer = "0.3"
serde = "1"
serde_derive = "1"
serde_json = "1"
chrono = "0.4"
hyper = "0.12"
bender_job = { git = "ssh://git@code.hfbk.net:4242/bendercode/bender-job.git" }
bender_mq = { git = "ssh://git@code.hfbk.net:4242/bendercode/bender-mq.git" }

[dependencies.amqp]
version = "0.1.2"
default-features = false